### ISSUE TITLE
Issue form nhập Thực vật

### ISSUE THREAD

**Issue by sangdv** [ngocdon0127/museum#43]
- Trường 8, 19, 33, 44/thời gian chế tác, 52: yêu cầu dd/mm/yyyy
- Trường 9: Tên Việt Nam (phổ thông)
- Trường 15: chưa cho phép chọn nhiều loại
- Trường 15, 20, 36: sai tips
- Trường 22, 24, 42: thiếu tips
- Trường 12 cần disable

**Comment by ngocdon0127** [comment]
Trường 15 (Loại mẫu vật) và trường 50 (Giá trị sử dụng) em đã chỉnh lại cho phép chọn nhiều loại rồi đấy ạ
