### ISSUE TITLE
Form nhập cổ sinh

### ISSUE THREAD

**Issue by quynh22021996** [ngocdon0127/museum#48]
2: Chưa có tips
8: Ngày định tên chưa đúng kiểu dữ liệu dd/mm/yyyy.
14: tips Sai 
20: thiếu tips
22: Sai tips
31: sai chính tả tips
44: thời gian quản lí chế tác: bỏ tips đi
48: tips bị thiếu
Sai số thứ tự các mục từ mục 47.

**Comment by sangdv** [comment]
@ngocdon0127  và @kevinhoa95 xem nhé

**Comment by sangdv** [comment]
@quynh22021996 thử nhập một mẫu cổ sinh điền tất cả các thông tin thử xem nhé

**Comment by kevinhoa95** [comment]
@sangdv 
Thưa thầy,
-  tips của từng form e đang sửa ạ
- Phần số thứ tự trước e có hỏi về form cổ sinh chỗ "Phân bố địa lý của taxon định loại (*)" khác với các form còn lại nên e không sửa ạ
- Phần thời gian sai định dạng thì có thể là do phần cài đặt thời gian trên máy tính làm việc, chứ trên máy em định dạng vẫn là dd/mm/yyyy ạ

**Comment by quynh22021996** [comment]
@kevinhoa95 
43: bỏ tips.
 Với ngày giờ, e mà đánh thẳng ngày h vào nếu e nhập 1 dãy số liên tiếp  khoảng 5-6 số không có dấu/,nó không báo sai gì cả, nhưng lại lưu thành 1 ngày nào đấy.

**Comment by ngocdon0127** [comment]
@quynh22021996  Về vụ đánh ngày sai vẫn nhận mình vừa fix rồi nhé. 👍  :-D

**Comment by quynh22021996** [comment]
@ngocdon0127  
43: bỏ tips
14: đánh vào 1 ký tự lưu nó không báo sai nhưng khi xem lại  bản thì nó không ghi ra số tiêu bản

**Comment by kevinhoa95** [comment]
@quynh22021996 
Trường 14 trong cổ sinh là trường disabled nên k nhận dữ liệu, mình đã fix rồi nhé.
