### ISSUE TITLE
Form nhập cổ sinh

### ISSUE THREAD

**Issue by sangdv** [ngocdon0127/museum#63]
+ Cổ sinh bắt lỗi sai, không nhập dữ liệu được
![1](https://cloud.githubusercontent.com/assets/10546154/23398570/a8a854b8-fdcf-11e6-93b5-811f5d39c043.png)
+ Số thực thì bắt lỗi như thế nào? Cả . và , đều được?
![1](https://cloud.githubusercontent.com/assets/10546154/23398849/ae6b54a8-fdd0-11e6-8127-3e9592f15fee.png)
+ 47, 48 cần chỉnh lại để 2 trường nhập nằm dưới tiêu đề

**Comment by sangdv** [comment]
Số thực thì bắt lỗi như thế nào? Cả . và , đều được?
![1](https://cloud.githubusercontent.com/assets/10546154/23398806/88a31e4a-fdd0-11e6-8d43-2cb0fe767a1c.png)

**Comment by ngocdon0127** [comment]
Cái thứ nhất bắt lỗi sai em chưa rõ là thầy nhập thế nào mà lại lỗi. Vì em cũng nhập các số như trong hình mà vẫn được ạ.
Cái thứ 2 thì khi gửi dữ liệu lên trên, server sẽ parse để ép nó thành số thực. VD 1.14.23.12,213 => 1.14 còn 2,14.12.3.1212.12..12,121,2,,12 => 2

**Comment by sangdv** [comment]
Nhiều người vẫn có thói quen dùng dấu , cho thập phân. Mình ép thế liệu có
sai ko?

Vào 28-02-2017 22:04, "Don Nguyen Ngoc" <notifications@github.com> đã viết:

Cái thứ nhất bắt lỗi sai em chưa rõ là thầy nhập thế nào mà lại lỗi. Vì em
cũng nhập các số như trong hình mà vẫn được ạ.
Cái thứ 2 thì khi gửi dữ liệu lên trên, server sẽ parse để ép nó thành số
thực. VD 1.14.23.12,213 => 1.14 còn 2,14.12.3.1212.12..12,121,2,,12 => 2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ngocdon0127/museum/issues/63#issuecomment-283063260>,
or mute the thread

**Comment by ngocdon0127** [comment]
Dạ. Chuẩn dùng dấu chấm để phân tách phần thập phân là chuẩn quốc tế rồi ạ. Em nghĩ rằng người nhập liệu cũng phải tuân thủ 1 số quy tắc cơ bản chứ không thể để họ tự ý thoải mái nhập liệu được ạ.

**Comment by sangdv** [comment]
Nhưng mình có thông báo cho họ phải nhập dấu chấm đâu mà họ biết. Thầy
tưởng dùng biểu thức chính quy sẽ bắt đc cái này chứ nhỉ.

Vào 01-03-2017 00:39, "Don Nguyen Ngoc" <notifications@github.com> đã viết:

**Comment by quynh22021996** [comment]
6:
Phân lớp, liên họ, phân họ,phân chi/phân giống: chưa có autocomplete
15: không chọn mà tự nhập được
24: kiểu này không nhập số nguyên không sai nhưng lưu thì mất phần sai
40: thông báo lỗi nhưng khi lưu thì vẫn lưu

**Comment by ngocdon0127** [comment]
6, 15, 40: Đã fix rồi Quỳnh nhé

**Comment by quynh22021996** [comment]
@ngocdon0127 
24: vẫn chưa đc sửa.
Lỗi khi in:
trường 23 Nếu không nhập thông tin khi in nó sẽ ra ký tự lạ.
Không nhập thông tin của trường nào thì tiêu đề trường đó không được in ra, như thế stt sẽ không theo lần lượt, e thấy nó hơi không đúng?

**Comment by ngocdon0127** [comment]
@quynh22021996 
24: Okie cái này loằng ngoằng bọn anh sẽ coi lại.
23: Đã sửa.
Trường nào không nhập thì ko in để khi đem in ra giấy sẽ đỡ tốn :-D. Bên bảo tàng yêu cầu thế mà. 
Còn stt thì tương ứng với form dữ liệu gốc để họ dễ kiểm kê ấy em.

**Comment by quynh22021996** [comment]
@ngocdon0127 
11: chưa có autocomplete
12: chưa có tips.
14: tips sai.
15: nhập 1 cái bất kỳ không báo lỗi nhưng lưu lại thì mất dữ liệu.
24: vẫn chưa sửa.
A ơi sao load lâu quá  :’(

**Comment by ngocdon0127** [comment]
11. 12 Anh thêm rồi nhé.
14. Anh tưởng "Thể hiện số lượng mẫu vật cùng loài trong CSDL đã lưu trữ" là đúng rồi chứ?
15. Vì chỉ được chọn 1 trong 3 loại "Mẫu nghiên cứu", "Mẫu trưng bày" và "Mẫu Type" nên không cho phép lưu loại khác.

Vấn đề load lâu bọn anh vừa chỉnh lại, nhưng cũng có thể là tại mạng nữa.
24. chưa fix. :octocat:  💃 💃 💃
