### ISSUE TITLE
Form nhập thổ nhưỡng

### ISSUE THREAD

**Issue by sangdv** [ngocdon0127/museum#64]
36. Chưa cho browse và chọn file
47, 48. Mới chỉ cho jpg và png
50. Mới chỉ cho avi và mp4
51/Hình ảnh đính kèm xử lý chế tác: Mới chỉ cho jpg và png
51/Đính kèm xử lý chế tác: thiếu docx
62. Chưa hoàn chỉnh ComboBox
65. Chưa AutoComplete
68. Chưa có file docx

Lưu ý các chỗ nhập file, chỗ nào họ đã ghi rõ kiểu file thì làm đúng như thế, còn ghi chung chung thì mình thống nhất như sau:
- dữ liệu ảnh thì nên cho một số định dạng như: jpg, bmp, png, tiff, raw, ...
- dữ liệu video thì nên cho một số định dạng: flv, avi, mp3, mp4, wmv, rm, ...

**Comment by ngocdon0127** [comment]
36. Lỗi này do Chrome thầy ạ. Bọn em đang nghiên cứu.
Các trường multimedia đã cho phép tải lên các định dạng tương ứng:
Ảnh: jpg | jpeg | gif | png | tif | tiff | raw | bmp | bpg
Video: mp4 | mpg | flv | webm | mkv | ogg | avi | mov | wmv | 3gp | m4v | rm
51. Đã thêm docx
38. Chưa hoàn chỉnh ComboBox. Cái này chắc là trường 62 ạ? Em đã hoàn thiện.

**Comment by sangdv** [comment]
37 sao lại thêm docx? Thầy tưởng 40 và 51 chứ?
39 chưa AutoComplete nữa

**Comment by ngocdon0127** [comment]
39 là trường ngày tháng mà thầy. Sao lại AutoComplete được ạ?
40 và 51 đã OK ạ.

**Comment by sangdv** [comment]
Ok, thầy nhầm. @kevinhoa95 
Tuy nhiên trường 62 yêu cầu Combobox: (**thu thập, hiến tặng, khác**) nhưng của mình lại hiện là (**thu thập, hiến tặng, trao đổi**)

**Comment by ngocdon0127** [comment]
Dạ, hiện tại ở trường 62 sẽ có sẵn 2 dòng là Thu thập, Hiến tặng để người nhập chọn. Nếu có giá trị khác thì họ có thể nhập trực tiếp vào ô input ạ.

![image](https://cloud.githubusercontent.com/assets/12444937/23587845/b513e15c-01e6-11e7-8c22-c713817658c8.png)

Việc làm thêm dòng "Khác" rồi hiện ra 1 ô text để người ta nhập vào khiến người nhập mất thêm 1 thao tác so với hiện tại, và việc lập trình cũng rắc rối hơn. Nên em nghĩ để thế này là ổn ạ.

**Comment by sangdv** [comment]
Ok Đôn
