### ISSUE TITLE
Form mẫu địa chất

### ISSUE THREAD

**Issue by chiennguyen196bg** [ngocdon0127/museum#69]
24. Nếu nhập tọa độ là số thập phân ở kiểu nhập độ phút giây thì bị chuyển sang dạng số thập phân mà không báo lỗi.
26. Bị giới hạn độ dài.
27. Không mở được file
43. Đính kèm xử lý chế tác: Chưa chọn được file
- Khi load lại trang hay chỉnh sửa không hiển thị các file đã tải lên.

**Comment by ngocdon0127** [comment]
26. Ghi chép thực địa: Anh thử chèn vào 36000 từ thì vẫn lưu được mà nhỉ?
![image](https://cloud.githubusercontent.com/assets/12444937/23583662/bc18533e-017d-11e7-8ccd-7ba852470dea.png)

**Comment by chiennguyen196bg** [comment]
Mấy cái mẫu chưa xuất được ra file a à.

**Comment by ngocdon0127** [comment]
Chú tích tích mấy cái checkbox ở bên trái chưa?
