### ISSUE TITLE
Form thực vật và nấm

### ISSUE THREAD

**Issue by huyentls1114** [ngocdon0127/museum#70]
6/Phân chi: Ko có autocomplete
15. Nhập mẫu bằng tay vẫn được
17. Không hiển thị lí do
24. kiểu dms khác kiểu dd
25. khi nhập 11.2.3 vẫn không báo lỗi
26. nhập kiểu float thì báo lỗi
36. Không nhập trường text, chỉ nhập ảnh(hoặc ngược lại) thì báo lỗi
37.như 36
38. Thiếu định dạng ảnh .esp, không báo kích thước ảnh vượt quá kích cỡ
40. Thiếu định dạng ảnh .esp, báo quá kích thước ảnh nhưng báo xong vẫn lưu
41. không báo kích thước ảnh vượt quá kích cỡ
42. thiếu lí do
44. không báo kích thước ảnh vượt quá kích cỡ
cột Thời gian xử lý, chế tác mẫu: không có form thời gian
cột Ảnh mẫu sau chế tác: không thông báo vượt quá kích cỡ
45. Vị trí lấy mẫu... + Mẫu DNA...: thiếu combobox
trình tự DNA:  không hiển thị file video
48. thiếu 1 string hoặc thiếu file thì sẽ báo lỗi
49.giống 48

**Comment by ngocdon0127** [comment]
Đã fix:
6/Phân chi: Ko có autocomplete
15. Nhập mẫu bằng tay vẫn được
36. 
38.
40.  
41.
44.
45. Đã fix Vị trí lấy mẫu + Mẫu DNA. **Trình tự DNA không hiển thị file video nghĩa là sao em?**
48, 49. Đã fix

**Comment by huyentls1114** [comment]
Em thấy chỗ kiểu dữ liệu là file đính kèm tức nghĩa là file nào cũng up lên được, nhưng lúc chọn file thì nó không hiển thị file video để tải lên ạ.

**Comment by ngocdon0127** [comment]
Mục này đợi thầy Thiệu hỏi lại bên kia đã, hiện tại anh đang giới hạn ảnh + doc/docx + pdf 🤒

**Comment by huyentls1114** [comment]
9.10.11.12. Thiếu auto complete
14. Số lượng tiêu bản điền số thực vẫn không báo lỗi
23. Thiếu trường quốc gia khác
24. chỗ nhập DMS nhập số thực vẫn không báo lỗi
31. Tải 2 file zip vẫn không báo lỗi
56. Không có lựa chọn khác
59. không yêu vầu auto complete lại thêm vào

**Comment by kevinhoa95** [comment]
@huyentls1114 
 - 14, 24: Lỗi bắt số nguyên a đang check lại
 - 56, 23: Khi user cần một lựa chọn khác thì họ nhập thẳng vào trường input  đó.
 - 31: Trường này là multiple e nhá
 - 59: Thêm vào thì càng tốt hơn chứ ✌️
