### ISSUE TITLE
Mục cấp quyền

### ISSUE THREAD

**Issue by huyentls1114** [ngocdon0127/museum#75]
Chú ý: đôi khi load trang thì web nó lỗi 
1. Tài khoản đăng kí mới không check xem email đúng hay sai ==
2. Tài khoản admin sau khi truy cập vào trang admin thì không trở về trang chủ được
3. Sau khi admin chuyển 1 tài khoản Pending User thành Normal User thì truy cập vào tải khoản đó vẫn như  Pending User, không có quyền thêm, sửa, xóa ...
4. Khi Normal User tạo ra mẫu vật: Phần lịch sử nhập liệu của Manager, của cả Admin cũng không lưu quá trình đó. 
5. Mục lịch sử nhập liệu của Manager, chỗ liên kết : click vào "Dữ liệu tại thời điểm này" thì ra web lỗi, 
chỗ Hành động :click vào cập nhật thì k ra gì cả.
7.Mục quản lí mẫu vật của Manager: vẫn chưa xuất được .doc với .xlsx

**Comment by ngocdon0127** [comment]
1. Đã fix
2. Đây anh mới thêm vào ✌️ 
![image](https://cloud.githubusercontent.com/assets/12444937/23834319/27e742f0-0787-11e7-8ae1-ab040119bb7f.png)
3. Trang quản trị chỉ là để quản lý cấp bậc user. Còn muốn cấp quyền thao tá với dữ liệu thì vẫn cần phải vào trang Cài đặt (/config) để điều chỉnh.
4. Lịch sử trước để nhầm link. Đáng lẽ phải lả /log/all. Đã fix
5. Trang lịch sử có mấy cái chữ xanh xanh ở 2 cột Nhân viên và Hành động là để lọc thôi. VD bấm vào Cập nhật thì nó sẽ lọc tất cả các log về Cập nhật, bấm mẫu động vật thì nó sẽ lọc các log liên quan đến mẫu động vật.
7. Cái này hình như vẫn xuất được mà nhỉ?
![image](https://cloud.githubusercontent.com/assets/12444937/23834367/f60d2de8-0787-11e7-9797-0538678bb8d3.png)
